---
- name: Create login.defs | os-05, os-05b
  template:
    src: 'etc/login.defs.j2'
    dest: '/etc/login.defs'
    owner: 'root'
    group: 'root'
    mode: '0444'
  when: os_login_defs_enabled | bool
  tags: login_defs

- name: Read local linux user database
  getent:
    database: passwd
    #creates a dict for each user containing UID/HOMEDIR etc...
  when: getent_passwd is undefined # skip this task if "getent" has run before

- name: extract system accounts from local user database
  loop: "{{ getent_passwd.keys()|list }}"
  when:  
    - getent_passwd[item][1]|int > 0
    - getent_passwd[item][1]|int <= os_auth_sys_uid_max|int
    - item is not in os_always_ignore_users     # skip users from "os_always_ignore_users" list (taken from role "vars")
    - item is not in os_ignore_users            # skip users from "os_ignore_users"        list (taken from role "defaults")
  set_fact:
    system_users: "{{ system_users|default([]) + [item] }}"

- name: remove shell+password for linux system accounts
  user:
    name: '{{ item }}'
    shell: '{{ os_nologin_shell_path }}'
    password: '*'
    createhome: false
  loop: "{{ system_users }}"

- name: extract regular (non-system) accounts from local user database
  loop: "{{ getent_passwd.keys()|list }}"
  when:  
    - getent_passwd[item][1]|int >= os_auth_uid_min|int
    - getent_passwd[item][1]|int <= os_auth_uid_max|int
    - item is not in os_always_ignore_users     # skip users from "os_always_ignore_users" list (taken from role "vars")
    - item is not in os_ignore_users            # skip users from "os_ignore_users"        list (taken from role "defaults")
  set_fact:
    regular_users: "{{ regular_users|default([]) + [item] }}"

- name: set ownership of user home directories to 0700
  file:
    mode: 0700
    owner: "{{ item }}"
    path: "{{ getent_passwd[item][4] }}"
    state: directory
  loop: "{{ regular_users }}"
  when: 
    - os_chmod_home_folders | bool
    - item not in os_ignore_home_folder_users|default([])

- name: Set password ageing for exisiting regular user accounts (system users have no password)
  user:
    name: "{{ item }}"
    password_expire_min: "{{ os_auth_pw_min_age }}"
    password_expire_max: "{{ os_auth_pw_max_age }}"
  loop: "{{ regular_users }}"
  when: 
    - os_user_pw_ageing
    - item not in os_users_without_password_ageing

- name: extract root account(s) from local user database
  loop: "{{ getent_passwd.keys()|list }}"
  when:  
    - getent_passwd[item][1]|int == 0
  set_fact:
    root_users: "{{ root_users|default([]) + [item] }}"

- name: Remove non-root users with UID=0
  user:
    name: "{{ item }}"
    state: absent
  loop: "{{ root_users }}"
  when: 
    - os_remove_additional_root_users|bool
    - root_users|length > 1
    - item != "root"

- name: set ownership of root user home directory(s) to 0700
  file:
    mode: 0700
    owner: "{{ item }}"
    path: "{{ getent_passwd[item][4] }}"
    state: directory
  loop: "{{ root_users }}"
  when: 
    - os_chmod_rootuser_home_folder | bool

- name: Set password ageing for root user(s)
  user:
    name: "{{ item }}"
    password_expire_min: "{{ os_auth_pw_min_age }}"
    password_expire_max: "{{ os_auth_pw_max_age }}"
  loop: "{{ root_users }}"
  when: os_rootuser_pw_ageing|bool
